# Generated by Django 4.0.3 on 2023-11-19 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_id_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='price',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='brand',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='edition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='no_of_owners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='transmission',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
