# Generated by Django 4.0.3 on 2023-12-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(default='https://images-platform.99static.com/pzfVOCfWSdCWxplUquFVXeUNeZs=/500x500/top/smart/99designs-contests-attachments/28/28767/attachment_28767406'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars\\guest.png', upload_to='avatars/'),
        ),
    ]
